// Code generated by sqlc. DO NOT EDIT.
// source: mempool.sql

package db

import (
	"context"
)

const deleteMempool = `-- name: DeleteMempool :exec
DELETE FROM transactions WHERE block_hash IS NULL
`

func (q *Queries) DeleteMempool(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMempool)
	return err
}
