// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"fmt"

	"github.com/handshake-labs/blockexplorer/pkg/types"
)

type CovenantAction string

const (
	CovenantActionNONE     CovenantAction = "NONE"
	CovenantActionCLAIM    CovenantAction = "CLAIM"
	CovenantActionOPEN     CovenantAction = "OPEN"
	CovenantActionBID      CovenantAction = "BID"
	CovenantActionREVEAL   CovenantAction = "REVEAL"
	CovenantActionREDEEM   CovenantAction = "REDEEM"
	CovenantActionREGISTER CovenantAction = "REGISTER"
	CovenantActionUPDATE   CovenantAction = "UPDATE"
	CovenantActionRENEW    CovenantAction = "RENEW"
	CovenantActionTRANSFER CovenantAction = "TRANSFER"
	CovenantActionFINALIZE CovenantAction = "FINALIZE"
	CovenantActionREVOKE   CovenantAction = "REVOKE"
)

func (e *CovenantAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CovenantAction(s)
	case string:
		*e = CovenantAction(s)
	default:
		return fmt.Errorf("unsupported scan type for CovenantAction: %T", src)
	}
	return nil
}

type Block struct {
	Hash           types.Bytes
	Height         int32
	Weight         int32
	Size           int64
	Version        int32
	HashMerkleRoot types.Bytes
	WitnessRoot    types.Bytes
	TreeRoot       types.Bytes
	ReservedRoot   types.Bytes
	Mask           types.Bytes
	Time           int32
	Bits           types.Bytes
	Difficulty     float64
	Chainwork      types.Bytes
	Nonce          int64
	ExtraNonce     types.Bytes
	Orphan         bool
}

type ReservedName struct {
	Name        types.Bytes
	OriginName  types.Bytes
	NameHash    types.Bytes
	ClaimAmount int64
}

type Transaction struct {
	Txid      types.Bytes
	WitnessTx types.Bytes
	Fee       int64
	Rate      int64
	BlockHash types.Bytes
	Index     int32
	Version   int32
	Locktime  int32
	Size      int64
}

type TxInput struct {
	Txid         types.Bytes
	Index        int64
	HashPrevout  types.Bytes
	IndexPrevout int64
	Sequence     int64
	BlockHash    types.Bytes
}

type TxOutput struct {
	Txid                 types.Bytes
	Index                int32
	Value                int64
	BlockHash            types.Bytes
	Address              string
	CovenantAction       CovenantAction
	CovenantNameHash     *types.Bytes
	CovenantHeight       *types.Bytes
	CovenantName         *types.Bytes
	CovenantBidHash      *types.Bytes
	CovenantNonce        *types.Bytes
	CovenantRecordData   *types.Bytes
	CovenantBlockHash    *types.Bytes
	CovenantVersion      *types.Bytes
	CovenantAddress      *types.Bytes
	CovenantClaimHeight  *types.Bytes
	CovenantRenewalCount *types.Bytes
}

type AuctionHistoryRow struct {
  Height int32 
  Txid types.Bytes
  CovenantName *types.Bytes
  LockupValue int64
  RevealValue NullInt
  // RevealValue int64
  CovenantAction *types.Bytes
  CovenantRecordData *types.Bytes
  CovenantNameHash *types.Bytes
}

type NullInt struct {
  Valid bool
  Value int64
}

type NameRow struct {
  OpenHeight int32
  CovenantNameHash types.Bytes
  CovenantName types.Bytes
  MaxLockup int64
  MaxRevealed int64
  BidCount int16
}

type RecordRow struct {
  Height int32
  CovenantRecordData types.Bytes
}

