// Code generated by sqlc. DO NOT EDIT.
// source: reserved_names.sql

package db

import (
	"context"

	"github.com/handshake-labs/blockexplorer/pkg/types"
)

const checkReservedName = `-- name: CheckReservedName :one
SELECT name, origin_name, name_hash, claim_amount
FROM reserved_names
WHERE name = $1
`

func (q *Queries) CheckReservedName(ctx context.Context, name types.Bytes) (ReservedName, error) {
	row := q.db.QueryRowContext(ctx, checkReservedName, name)
	var i ReservedName
	err := row.Scan(
		&i.Name,
		&i.OriginName,
		&i.NameHash,
		&i.ClaimAmount,
	)
	return i, err
}

const checkReservedNameHash = `-- name: CheckReservedNameHash :one
SELECT name, origin_name, name_hash, claim_amount
FROM reserved_names
WHERE name_hash = $1
`

func (q *Queries) CheckReservedNameHash(ctx context.Context, nameHash types.Bytes) (ReservedName, error) {
	row := q.db.QueryRowContext(ctx, checkReservedNameHash, nameHash)
	var i ReservedName
	err := row.Scan(
		&i.Name,
		&i.OriginName,
		&i.NameHash,
		&i.ClaimAmount,
	)
	return i, err
}
