// Code generated by sqlc. DO NOT EDIT.
// source: transactions.sql

package db

import (
	"context"

	"github.com/handshake-labs/blockexplorer/pkg/types"
)

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (hash, block_hash, witness_tx, fee, rate, version, locktime, size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertTransactionParams struct {
	Hash      types.Bytes
	BlockHash types.Bytes
	WitnessTx types.Bytes
	Fee       int64
	Rate      int64
	Version   int32
	Locktime  int32
	Size      int64
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransaction,
		arg.Hash,
		arg.BlockHash,
		arg.WitnessTx,
		arg.Fee,
		arg.Rate,
		arg.Version,
		arg.Locktime,
		arg.Size,
	)
	return err
}
