// Code generated by sqlc. DO NOT EDIT.
// source: tx_inputs.sql

package db

import (
	"context"

	"github.com/handshake-labs/blockexplorer/pkg/types"
)

const getTxInputsByTxHash = `-- name: GetTxInputsByTxHash :many
SELECT tx_hash, index, hash_prevout, index_prevout, sequence
FROM tx_inputs
WHERE tx_hash = $1
ORDER BY index
`

func (q *Queries) GetTxInputsByTxHash(ctx context.Context, txHash types.Bytes) ([]TxInput, error) {
	rows, err := q.db.QueryContext(ctx, getTxInputsByTxHash, txHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TxInput{}
	for rows.Next() {
		var i TxInput
		if err := rows.Scan(
			&i.TxHash,
			&i.Index,
			&i.HashPrevout,
			&i.IndexPrevout,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTxInput = `-- name: InsertTxInput :exec
INSERT INTO tx_inputs (tx_hash, index, hash_prevout, index_prevout, sequence)
VALUES ($1, $2, $3, $4, $5)
`

type InsertTxInputParams struct {
	TxHash       types.Bytes
	Index        int32
	HashPrevout  types.Bytes
	IndexPrevout int64
	Sequence     int64
}

func (q *Queries) InsertTxInput(ctx context.Context, arg InsertTxInputParams) error {
	_, err := q.db.ExecContext(ctx, insertTxInput,
		arg.TxHash,
		arg.Index,
		arg.HashPrevout,
		arg.IndexPrevout,
		arg.Sequence,
	)
	return err
}
