FROM golang:1.14.3-alpine AS build
RUN apk add gcc 
RUN apk add g++ 
WORKDIR /src
COPY . .


RUN go get github.com/pressly/goose/cmd/goose
RUN go build  ./cmd/sync 
ENTRYPOINT ["goose -dir sql/schema postgres $POSTGRES_URI up", "./sync"]
