FROM golang:1.14.3-alpine AS build
WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN go build github.com/handshake-labs/blockexplorer/cmd/rest

FROM alpine
COPY --from=build /src/rest .
ENTRYPOINT ["./rest"]

test
